wandb_version: 1

logger:
  desc: null
  value:
    base_exp_path: results
    use_console: 'True'
    use_tb: 'False'
    use_json: 'False'
    use_neptune: 'False'
    use_wandb: 'True'
    kwargs:
      project: None
      tags: '[''stoix'']'
      detailed_logging: 'False'
      json_path: None
      upload_json_data: 'False'
    checkpointing:
      save_model: 'False'
      save_args:
        save_interval_steps: '1'
        max_to_keep: '1'
        keep_period: None
        checkpoint_uid: None
      load_model: 'False'
      load_args:
        checkpoint_uid: ''
arch:
  desc: null
  value:
    seed: '42'
    update_batch_size: '1'
    total_num_envs: '1024'
    total_timesteps: '10000000.0'
    num_updates: '610.0'
    evaluation_greedy: 'False'
    num_eval_episodes: '128'
    num_evaluation: '50'
    absolute_metric: 'True'
    num_envs: '1024'
    num_updates_per_eval: '12.0'
system:
  desc: null
  value:
    system_name: ff_ppo
    actor_lr: '0.0003'
    critic_lr: '0.0003'
    rollout_length: '16'
    epochs: '4'
    num_minibatches: '16'
    gamma: '0.99'
    gae_lambda: '0.95'
    clip_eps: '0.2'
    ent_coef: '0.001'
    vf_coef: '1.0'
    max_grad_norm: '0.5'
    decay_learning_rates: 'False'
    standardize_advantages: 'True'
    kl_penalty_coef: '3.0'
    action_dim: '4'
network:
  desc: null
  value:
    actor_network:
      pre_torso:
        _target_: stoix.networks.resnet.VisualResNetTorso
        channels_per_group: '[256]'
        blocks_per_group: '[4]'
        use_layer_norm: 'True'
        activation: silu
      action_head:
        _target_: stoix.networks.heads.CategoricalHead
    critic_network:
      pre_torso:
        _target_: stoix.networks.resnet.VisualResNetTorso
        channels_per_group: '[256]'
        blocks_per_group: '[4]'
        use_layer_norm: 'True'
        activation: silu
      critic_head:
        _target_: stoix.networks.heads.ScalarCriticHead
env:
  desc: null
  value:
    env_name: jumanji
    observation_attribute: grid
    multi_agent: 'False'
    scenario:
      name: Sokoban-v0
      task_name: sokoban
    kwargs: {}
    eval_metric: episode_return
num_devices:
  desc: null
  value: '1'
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720730463
    t:
      1:
      - 12
      - 45
      - 49
      - 50
      - 55
      2:
      - 12
      - 45
      - 49
      - 50
      - 55
      3:
      - 2
      - 15
      - 16
      - 23
      - 61
      4: 3.10.14
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
