# ---ResNet---
actor_network:
  pre_torso:
    _target_: stoix.networks.resnet.VisualResNetTorso
    channels_per_group: [256]
    blocks_per_group: [4]
    use_layer_norm: True
    activation: silu
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.resnet.VisualResNetTorso
    channels_per_group: [256]
    blocks_per_group: [4]
    use_layer_norm: True
    activation: silu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
